//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anticipo
    {
        public int IDANTICIPO { get; set; }
        public Nullable<int> IDDATOSLICITACION { get; set; }
        public Nullable<decimal> ANTICIPO1 { get; set; }
        public Nullable<decimal> ANTICIPOINICIO { get; set; }
        public Nullable<decimal> ANTICIPOMATERIALES { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> CAPITALMINIMO { get; set; }
    
        public virtual DatosLicitacion DatosLicitacion { get; set; }
    }
}
