//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.Fianzas = new HashSet<Fianza>();
            this.Inscritoes = new HashSet<Inscrito>();
            this.Seguimientoes = new HashSet<Seguimiento>();
        }
    
        public int IDCONTRATO { get; set; }
        public Nullable<int> IDOFICIOSAUT { get; set; }
        public string NOCONTRATO { get; set; }
        public Nullable<int> IDTIPOCONTRATO { get; set; }
        public string DESCRIPCIONOBRA { get; set; }
        public Nullable<int> OFICIOAPROBACION { get; set; }
        public Nullable<System.DateTime> FECHAAPROB { get; set; }
        public Nullable<System.DateTime> FECHARECAPROB { get; set; }
        public Nullable<System.DateTime> INICIOOBRA { get; set; }
        public Nullable<System.DateTime> FINOBRA { get; set; }
        public Nullable<int> DIASCONTRATO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<int> IDMUNICIPIO { get; set; }
        public Nullable<int> HABILITADO { get; set; }
        public string NOTASACLARATORIAS { get; set; }
        public Nullable<int> IDDATOSLICITACION { get; set; }
    
        public virtual DatosLicitacion DatosLicitacion { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual OficiosAut OficiosAut { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fianza> Fianzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscrito> Inscritoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento> Seguimientoes { get; set; }
    }
}
