//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convocatoria
    {
        public int IDCONVOCATORIA { get; set; }
        public Nullable<int> IDDATOSLICITACION { get; set; }
        public Nullable<System.DateTime> PROCESO { get; set; }
        public Nullable<System.DateTime> PROCESOAUT { get; set; }
        public Nullable<System.DateTime> CONVOCATORIADO { get; set; }
        public Nullable<System.DateTime> ENVIOCN { get; set; }
        public Nullable<System.DateTime> PUBLICACION { get; set; }
        public Nullable<System.DateTime> FLIMITE1 { get; set; }
        public Nullable<System.DateTime> FLIMITE2 { get; set; }
        public Nullable<System.DateTime> RECEPCIONLICITAR { get; set; }
    
        public virtual DatosLicitacion DatosLicitacion { get; set; }
    }
}
