//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosLicitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosLicitacion()
        {
            this.Anticipoes = new HashSet<Anticipo>();
            this.Canceladoes = new HashSet<Cancelado>();
            this.Convocatorias = new HashSet<Convocatoria>();
            this.VisitaProgs = new HashSet<VisitaProg>();
        }
    
        public int IDDATOSLICITACION { get; set; }
        public string NOPROCESO { get; set; }
        public Nullable<int> IDCONTRATO { get; set; }
        public Nullable<int> PLANOS { get; set; }
        public Nullable<int> ESPECIFICACIONES { get; set; }
        public string NOTASACLARATORIAS { get; set; }
        public Nullable<int> IDPROCEDIMIENTO { get; set; }
        public Nullable<int> IDAÑO { get; set; }
        public Nullable<int> IDSOLICITANTETC { get; set; }
        public Nullable<int> IDTIPOOBRA { get; set; }
        public Nullable<int> IDNIVELOBRA { get; set; }
        public Nullable<int> IDESPOBRA { get; set; }
        public Nullable<int> IDDIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anticipo> Anticipoes { get; set; }
        public virtual Año Año { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelado> Canceladoes { get; set; }
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Convocatoria> Convocatorias { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual EspObra EspObra { get; set; }
        public virtual NivelObra NivelObra { get; set; }
        public virtual Procedimiento Procedimiento { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual TipoObra TipoObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitaProg> VisitaProgs { get; set; }
    }
}
