//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosMoral
    {
        public int IDDATOSMORAL { get; set; }
        public Nullable<int> ACTACONSTITUTIVA { get; set; }
        public Nullable<System.DateTime> FECHAACTA { get; set; }
        public Nullable<int> NOTARIONUM { get; set; }
        public string NOTARIONOMBRE { get; set; }
        public Nullable<int> REGPUBLICO { get; set; }
        public Nullable<int> IDMUNICIPIO { get; set; }
        public Nullable<int> IDCONTRATISTA { get; set; }
    
        public virtual Contratista Contratista { get; set; }
        public virtual Municipio Municipio { get; set; }
    }
}
