//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosPoder
    {
        public int IDDATOSPODER { get; set; }
        public Nullable<int> IDREPRESENTA { get; set; }
        public Nullable<int> PODEREP { get; set; }
        public Nullable<int> NOTARIONO { get; set; }
        public string NOTARIONOMBRE { get; set; }
        public Nullable<int> IDMUNICIPIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string PARTIDA { get; set; }
        public string FOLIO { get; set; }
        public string LIBRO { get; set; }
        public string SECCION { get; set; }
        public string PUBLICONO { get; set; }
        public string FMERCANTIL { get; set; }
    
        public virtual DatosRepresenta DatosRepresenta { get; set; }
        public virtual Municipio Municipio { get; set; }
    }
}
