//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fianza
    {
        public int IDFIANZA { get; set; }
        public Nullable<int> ANUM { get; set; }
        public Nullable<decimal> AIMPORTE { get; set; }
        public Nullable<System.DateTime> AFECHA { get; set; }
        public Nullable<int> IDAFIANZADORAA { get; set; }
        public Nullable<int> CNUMERO { get; set; }
        public Nullable<decimal> CIMPORTE { get; set; }
        public Nullable<System.DateTime> CFECHA { get; set; }
        public Nullable<int> IDCONTRATO { get; set; }
        public Nullable<int> IDAFIAZADORAC { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
