//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuenteFin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FuenteFin()
        {
            this.MontoFins = new HashSet<MontoFin>();
        }
    
        public int IDFUENTEFIN { get; set; }
        public string FUENTEFIN1 { get; set; }
        public Nullable<int> IDESTRUCTURAFIN { get; set; }
    
        public virtual EstructuraFin EstructuraFin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MontoFin> MontoFins { get; set; }
    }
}
