//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MontoFin
    {
        public int IDMONTOFIN { get; set; }
        public Nullable<int> IDOFICIOSAUT { get; set; }
        public Nullable<int> IDFUENTEFIN { get; set; }
        public Nullable<int> IDESTRUCTURAFIN { get; set; }
        public Nullable<decimal> MONTO { get; set; }
    
        public virtual FuenteFin FuenteFin { get; set; }
        public virtual OficiosAut OficiosAut { get; set; }
    }
}
