//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OficiosAut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OficiosAut()
        {
            this.Contratoes = new HashSet<Contrato>();
            this.MontoFins = new HashSet<MontoFin>();
        }
    
        public int IDOFICIOSAUT { get; set; }
        public string OFICIOAUT { get; set; }
        public Nullable<System.DateTime> FECAUTORIZACION { get; set; }
        public Nullable<System.DateTime> FECRECIBIDO { get; set; }
        public Nullable<int> NUMASIGNACION { get; set; }
        public Nullable<int> NUMOBRA { get; set; }
        public string DESCOBRA { get; set; }
        public Nullable<int> IDAUTORIZA { get; set; }
        public Nullable<decimal> MONTOAUTORIZADO { get; set; }
        public Nullable<int> IDPROGRAMA { get; set; }
        public Nullable<int> IDMUNICIPIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contratoes { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Autoriza Autoriza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MontoFin> MontoFins { get; set; }
        public virtual Programa Programa { get; set; }
    }
}
