//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public int IDSEGUIMIENTO { get; set; }
        public Nullable<int> IDCONTRATO { get; set; }
        public Nullable<System.DateTime> RECPDOC { get; set; }
        public Nullable<System.DateTime> RECPPRE { get; set; }
        public Nullable<System.DateTime> ELABORADO { get; set; }
        public Nullable<System.DateTime> ENTREGA { get; set; }
        public Nullable<System.DateTime> DEVOLUCION { get; set; }
        public Nullable<System.DateTime> FIRMADIRECCION { get; set; }
        public Nullable<System.DateTime> FIRMASECRE { get; set; }
        public Nullable<System.DateTime> AUTSECRE { get; set; }
        public Nullable<System.DateTime> CAPTURASIIP { get; set; }
        public Nullable<System.DateTime> CAPTURASIIP2 { get; set; }
        public Nullable<System.DateTime> ENVIOFINANZAS { get; set; }
        public Nullable<System.DateTime> AJURIDICO { get; set; }
        public Nullable<System.DateTime> REVJURIDICO { get; set; }
        public Nullable<int> CONSULTASAT { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
