//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IDUSUARIO { get; set; }
        public string USUARIO1 { get; set; }
        public string CONTRA { get; set; }
        public string DESCRIPCION { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> IDRESPONSABILIDAD { get; set; }
        public Nullable<int> ACTIVO { get; set; }
    
        public virtual Responsabilidad Responsabilidad { get; set; }
    }
}
