//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcursosContratos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaProg
    {
        public int IDVISITAPROG { get; set; }
        public Nullable<int> IDDATOSLICITACION { get; set; }
        public Nullable<System.DateTime> VISITAF { get; set; }
        public string VISITAH { get; set; }
        public Nullable<int> IDDIRECCION { get; set; }
        public Nullable<System.DateTime> JACFECHA { get; set; }
        public string JACHORA { get; set; }
        public Nullable<System.DateTime> ATECFECHA { get; set; }
        public string ATECHORA { get; set; }
        public Nullable<System.DateTime> ACTFALLAFECHA { get; set; }
        public string ACTFALLAHORA { get; set; }
    
        public virtual DatosLicitacion DatosLicitacion { get; set; }
    }
}
